pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url "https://www.jitpack.io" }
        mavenCentral()
        gradlePluginPortal()
        maven {
            allowInsecureProtocol = true
            url "http://maven.geelib.360.cn/nexus/repository/replugin/"
        }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public/' }
        google()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
        jcenter()
        maven {
            url 'https://maven.hanana2.link:2053/releases'
        }
        maven { url 'https://artifact.bytedance.com/repository/releases/' }
        flatDir {
            dirs 'libs'  // 指定本地仓库路径
        }
        maven {
            allowInsecureProtocol = true
            url "http://maven.geelib.360.cn/nexus/repository/replugin/"
        }
    }
}
rootProject.name = "ottohub_andriod"
include ':app'
